services:

    #
    # Controllers
    #
    paymentsuite.freepayment.payment_controller:
        class: PaymentSuite\FreePaymentBundle\Controller\PaymentController
        arguments:
            - "@paymentsuite.freepayment.manager"
            - "@paymentsuite.freepayment.route_success"
            - "@paymentsuite.bridge"
            - "@router"
            - "@paymentsuite.order.payment_setter"
            - "@kernel"
            - "%create_order_with_freepayment%"
