paymentsuite_bankwire_execute:
    path: /payment/bankwire/execute
    defaults:
        _controller: paymentsuite.bankwire.payment_controller:executeAction

bankwire_store_homepage:
    path: /orders/{id}/thanks
    defaults: { _controller: plugin.bankwire.bankwire_controller:viewAction, 'thanks': true }
    requirements:
      orderId: '\d+'

